"""adding views to Book

Revision ID: 072242487887
Revises: 098e0d609b3d
Create Date: 2023-10-07 12:00:17.764188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072242487887'
down_revision = '098e0d609b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
